name: Gradle Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up JDK 8
        uses: actions/setup-java@main
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git autoconf automake libtool build-essential
          sudo apt-get install -y gcc make

      - name: Download and install Android SDK
        run: |
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
          unzip sdk-tools-linux-3859397.zip
          rm sdk-tools-linux-3859397.zip

      - name: Set environment variables
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$ANDROID_HOME/tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          echo "$HOME/android-sdk/tools/bin" >> $GITHUB_PATH

      - name: Install Android SDK components
        run: |
          yes | $ANDROID_HOME/tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses
          $ANDROID_HOME/tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-23"

      - name: Download and install NDK r25c
        run: |
          cd $HOME
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip -d /opt/android-sdk-linux_x86/
          rm android-ndk-r25c-linux.zip

      - name: Install Apache Ant
        run: |
          wget https://downloads.apache.org/ant/binaries/apache-ant-1.10.14-bin.tar.bz2
          tar -xvjf apache-ant-1.10.14-bin.tar.bz2 -C /opt/
          echo "/opt/apache-ant-1.10.14/bin" >> $GITHUB_PATH
          rm apache-ant-1.10.14-bin.tar.bz2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Initialize and update git submodules
        run: |
          git submodule init
          git submodule update

      - name: Build external dependencies
        run: |
          cd external
          export PATH=/opt/android-sdk-linux_x86/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          export NDK=/opt/android-sdk-linux_x86/android-ndk-r25c
          make

      - name: Cache Gradle dependencies
        uses: actions/cache@main
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build APK
        uses: gradle/gradle-build-action@main
        with:
          arguments: build

      - name: Upload APK
        uses: actions/upload-artifact@main
        with:
          name: apk
          path: app/build/outputs/apk
