name: Gradle Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git autoconf automake libtool build-essential
          sudo apt-get install -y gcc make

      - name: Download and install Android SDK
        run: |
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
          unzip sdk-tools-linux-3859397.zip
          rm sdk-tools-linux-3859397.zip

      - name: Set environment variables
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$ANDROID_HOME/tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          echo "$HOME/android-sdk/tools/bin" >> $GITHUB_PATH  # Add this line

      - name: Install Android SDK components
        run: |
          yes | $ANDROID_HOME/tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses  # Updated command
          $ANDROID_HOME/tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-23"  # Updated command

      - name: Download and install NDK r16b
        run: |
          cd $HOME
          wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip
          unzip android-ndk-r16b-linux-x86_64.zip -d /opt/android-sdk-linux_x86/
          rm android-ndk-r16b-linux-x86_64.zip

      - name: Install Apache Ant
        run: |
          wget https://downloads.apache.org//ant/binaries/apache-ant-1.10.9-bin.zip
          unzip apache-ant-1.10.9-bin.zip -d /opt/
          echo "/opt/apache-ant-1.10.9/bin" >> $GITHUB_PATH
          rm apache-ant-1.10.9-bin.zip

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Initialize and update git submodules
        run: |
          git submodule init
          git submodule update

      - name: Build external dependencies
        run: make -C external

      - name: Cache Gradle dependencies
        uses: actions/cache@main
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build APK
        uses: gradle/gradle-build-action@main
        with:
          arguments: build

      - name: Upload APK
        uses: actions/upload-artifact@main
        with:
          name: apk
          path: app/build/outputs/apk
